# Import numpy as np and see the version


In [2]:
import numpy as np
print(np.__version__)

1.17.2


#  How to create a 1D array?

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# How to create a boolean array

In [6]:
np.full((3,3), fill_value = True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# How to extract items that satisfy a given condition from 1D array?

Extract all odd numbers from array

In [8]:
arr = np.arange(20)
arr[arr % 2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

# How to replace items that satisfy a condition with another value in numpy array?

Replace all odd numbers in array with -1

In [11]:
arr = np.arange(20)
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14, -1, 16,
       -1, 18, -1])

#  How to replace items that satisfy a condition without affecting the original array?

Replace all odd numbers in arr with -1 without changing array

In [14]:
array = np.arange(20)
odd = np.where(array %2 == 1, -1, array)
print('odd', odd)
print('array', array)

odd [ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1]
array [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


#  How to reshape an array?

In [17]:
arr = np.arange(10)
print('Array befor reshaping',arr)
arr = np.reshape(arr, (2,5))
print('Array after reshaping')
print(arr)

Array befor reshaping [0 1 2 3 4 5 6 7 8 9]
Array after reshaping
[[0 1 2 3 4]
 [5 6 7 8 9]]


# How to stack two arrays vertically?

In [18]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [21]:
# Method 1:
np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
# Method 2:
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
# Method 3:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# How to stack two arrays horizontally

In [26]:
np.concatenate([a,b], axis = 1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [27]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [28]:
np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# How to generate custom sequences in numpy without hardcoding?

Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

a = np.array([1,2,3])`


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [37]:
a = np.array([1,2,3])
np.hstack([np.repeat(a, 3), np.tile(a, 3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# What is np.tile?

In [43]:
np.tile(np.arange(10), 2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Indexing

Accessing the array elements

In [44]:
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [47]:
arr[1][3]

8

In [51]:
arr[1:, :3]

array([[5, 6, 7]])

In [54]:
arr[1:]=100

In [55]:
arr

array([[  0,   1,   2,   3,   4],
       [100, 100, 100, 100, 100]])

# How to get the common items between two python numpy arrays?

In [56]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [60]:
np.intersect1d(a,b)

array([2, 4])

# How to remove from one array those items that exist in another?

In [61]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [65]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])